### ISSUE TITLE
Problem with different packages for NodeKey

### ISSUE THREAD

**Issue by SergeyLee** [RestComm/cluster#4]
NodeKey in Infinispan 5.2.1.Final (JBoss 7.2.0.Final) is in package org.infinispan.tree, but in Infinispan 8.1.0.Final (WildFly 10.0.0.Final) is in package org.infinispan.tree.impl.
I used Reflection for invoking methods like getContents() and getFqn().

**Comment by satanatoly** [comment]
Closing due to reworked cluster that does not uses tree from inifinispan
